# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_frame.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_frame.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13message_frame.proto\"?\n\x05\x46rame\x12\x10\n\x08\x66rameLen\x18\x01 \x01(\x05\x12$\n\rframeMessages\x18\x02 \x03(\x0b\x32\r.FrameMessage\"^\n\x0c\x46rameMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x1e\n\x0bhandMessage\x18\x02 \x01(\x0b\x32\t.handData\x12\"\n\rdeviceMessage\x18\x03 \x01(\x0b\x32\x0b.deviceData\"\xed\x01\n\x08handData\x12\x14\n\x0cthumb_rotate\x18\x03 \x01(\x02\x12\x13\n\x0bthumb_split\x18\x04 \x01(\x02\x12\x12\n\nthumb_bend\x18\x05 \x01(\x02\x12\x13\n\x0bindex_split\x18\x06 \x01(\x02\x12\x12\n\nindex_bend\x18\x07 \x01(\x02\x12\x14\n\x0cmiddle_split\x18\x08 \x01(\x02\x12\x13\n\x0bmiddle_bend\x18\t \x01(\x02\x12\x12\n\nring_split\x18\n \x01(\x02\x12\x11\n\tring_bend\x18\x0b \x01(\x02\x12\x13\n\x0bpinky_split\x18\x0c \x01(\x02\x12\x12\n\npinky_bend\x18\r \x01(\x02\"5\n\ndeviceData\x12\x0f\n\x07isRight\x18\x02 \x01(\x08\x12\x16\n\x0e\x62\x61tteryPercent\x18\x03 \x01(\x05\x62\x06proto3')
)




_FRAME = _descriptor.Descriptor(
  name='Frame',
  full_name='Frame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frameLen', full_name='Frame.frameLen', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frameMessages', full_name='Frame.frameMessages', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=86,
)


_FRAMEMESSAGE = _descriptor.Descriptor(
  name='FrameMessage',
  full_name='FrameMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='FrameMessage.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='handMessage', full_name='FrameMessage.handMessage', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deviceMessage', full_name='FrameMessage.deviceMessage', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=182,
)


_HANDDATA = _descriptor.Descriptor(
  name='handData',
  full_name='handData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='thumb_rotate', full_name='handData.thumb_rotate', index=0,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thumb_split', full_name='handData.thumb_split', index=1,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thumb_bend', full_name='handData.thumb_bend', index=2,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index_split', full_name='handData.index_split', index=3,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index_bend', full_name='handData.index_bend', index=4,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='middle_split', full_name='handData.middle_split', index=5,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='middle_bend', full_name='handData.middle_bend', index=6,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ring_split', full_name='handData.ring_split', index=7,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ring_bend', full_name='handData.ring_bend', index=8,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pinky_split', full_name='handData.pinky_split', index=9,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pinky_bend', full_name='handData.pinky_bend', index=10,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=422,
)


_DEVICEDATA = _descriptor.Descriptor(
  name='deviceData',
  full_name='deviceData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isRight', full_name='deviceData.isRight', index=0,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batteryPercent', full_name='deviceData.batteryPercent', index=1,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=424,
  serialized_end=477,
)

_FRAME.fields_by_name['frameMessages'].message_type = _FRAMEMESSAGE
_FRAMEMESSAGE.fields_by_name['handMessage'].message_type = _HANDDATA
_FRAMEMESSAGE.fields_by_name['deviceMessage'].message_type = _DEVICEDATA
DESCRIPTOR.message_types_by_name['Frame'] = _FRAME
DESCRIPTOR.message_types_by_name['FrameMessage'] = _FRAMEMESSAGE
DESCRIPTOR.message_types_by_name['handData'] = _HANDDATA
DESCRIPTOR.message_types_by_name['deviceData'] = _DEVICEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Frame = _reflection.GeneratedProtocolMessageType('Frame', (_message.Message,), {
  'DESCRIPTOR' : _FRAME,
  '__module__' : 'message_frame_pb2'
  # @@protoc_insertion_point(class_scope:Frame)
  })
_sym_db.RegisterMessage(Frame)

FrameMessage = _reflection.GeneratedProtocolMessageType('FrameMessage', (_message.Message,), {
  'DESCRIPTOR' : _FRAMEMESSAGE,
  '__module__' : 'message_frame_pb2'
  # @@protoc_insertion_point(class_scope:FrameMessage)
  })
_sym_db.RegisterMessage(FrameMessage)

handData = _reflection.GeneratedProtocolMessageType('handData', (_message.Message,), {
  'DESCRIPTOR' : _HANDDATA,
  '__module__' : 'message_frame_pb2'
  # @@protoc_insertion_point(class_scope:handData)
  })
_sym_db.RegisterMessage(handData)

deviceData = _reflection.GeneratedProtocolMessageType('deviceData', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEDATA,
  '__module__' : 'message_frame_pb2'
  # @@protoc_insertion_point(class_scope:deviceData)
  })
_sym_db.RegisterMessage(deviceData)


# @@protoc_insertion_point(module_scope)
