# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctrl_command.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctrl_command.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12\x63trl_command.proto\"\x99\x01\n\x0e\x43ommandControl\x12\n\n\x02id\x18\x01 \x01(\x05\x12,\n\x11impedance_command\x18\x02 \x03(\x0b\x32\x11.ImpedanceControl\x12&\n\x0erumble_command\x18\x03 \x03(\x0b\x32\x0e.RumbleControl\x12%\n\x0eother_messages\x18\x04 \x03(\x0b\x32\r.OtherControl\"\xf9\x01\n\rRumbleControl\x12!\n\x05Thumb\x18\x01 \x01(\x0b\x32\x12.RumbleControlData\x12!\n\x05Index\x18\x02 \x01(\x0b\x32\x12.RumbleControlData\x12\"\n\x06Middle\x18\x03 \x01(\x0b\x32\x12.RumbleControlData\x12 \n\x04Ring\x18\x04 \x01(\x0b\x32\x12.RumbleControlData\x12!\n\x05Pinky\x18\x05 \x01(\x0b\x32\x12.RumbleControlData\x12&\n\nUtilRumble\x18\x06 \x03(\x0b\x32\x12.RumbleControlData\x12\x11\n\thas_index\x18\x07 \x01(\x08\"^\n\x11RumbleControlData\x12\x0f\n\x07is_open\x18\x01 \x01(\x08\x12\x16\n\x0erepeated_times\x18\x02 \x01(\x05\x12\x0e\n\x06volume\x18\x03 \x01(\x02\x12\x10\n\x08wavetype\x18\x04 \x01(\x05\"\xe3\x01\n\x10ImpedanceControl\x12$\n\x05Thumb\x18\x01 \x01(\x0b\x32\x15.ImpedanceControlData\x12$\n\x05Index\x18\x02 \x01(\x0b\x32\x15.ImpedanceControlData\x12%\n\x06Middle\x18\x03 \x01(\x0b\x32\x15.ImpedanceControlData\x12#\n\x04Ring\x18\x04 \x01(\x0b\x32\x15.ImpedanceControlData\x12$\n\x05Pinky\x18\x05 \x01(\x0b\x32\x15.ImpedanceControlData\x12\x11\n\thas_index\x18\x06 \x01(\x08\";\n\x14ImpedanceControlData\x12\x11\n\tStiffness\x18\x01 \x01(\x02\x12\x10\n\x08SetPoint\x18\x02 \x01(\x02\";\n\x0cOtherControl\x12\x14\n\x0c\x63ontrol_type\x18\x01 \x01(\x02\x12\x15\n\rcontrol_value\x18\x02 \x01(\x02\x62\x06proto3')
)




_COMMANDCONTROL = _descriptor.Descriptor(
  name='CommandControl',
  full_name='CommandControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CommandControl.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='impedance_command', full_name='CommandControl.impedance_command', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rumble_command', full_name='CommandControl.rumble_command', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='other_messages', full_name='CommandControl.other_messages', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=176,
)


_RUMBLECONTROL = _descriptor.Descriptor(
  name='RumbleControl',
  full_name='RumbleControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Thumb', full_name='RumbleControl.Thumb', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Index', full_name='RumbleControl.Index', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Middle', full_name='RumbleControl.Middle', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Ring', full_name='RumbleControl.Ring', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Pinky', full_name='RumbleControl.Pinky', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='UtilRumble', full_name='RumbleControl.UtilRumble', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='has_index', full_name='RumbleControl.has_index', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=428,
)


_RUMBLECONTROLDATA = _descriptor.Descriptor(
  name='RumbleControlData',
  full_name='RumbleControlData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_open', full_name='RumbleControlData.is_open', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='repeated_times', full_name='RumbleControlData.repeated_times', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='volume', full_name='RumbleControlData.volume', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wavetype', full_name='RumbleControlData.wavetype', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=430,
  serialized_end=524,
)


_IMPEDANCECONTROL = _descriptor.Descriptor(
  name='ImpedanceControl',
  full_name='ImpedanceControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Thumb', full_name='ImpedanceControl.Thumb', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Index', full_name='ImpedanceControl.Index', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Middle', full_name='ImpedanceControl.Middle', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Ring', full_name='ImpedanceControl.Ring', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Pinky', full_name='ImpedanceControl.Pinky', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='has_index', full_name='ImpedanceControl.has_index', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=527,
  serialized_end=754,
)


_IMPEDANCECONTROLDATA = _descriptor.Descriptor(
  name='ImpedanceControlData',
  full_name='ImpedanceControlData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Stiffness', full_name='ImpedanceControlData.Stiffness', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SetPoint', full_name='ImpedanceControlData.SetPoint', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=756,
  serialized_end=815,
)


_OTHERCONTROL = _descriptor.Descriptor(
  name='OtherControl',
  full_name='OtherControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='control_type', full_name='OtherControl.control_type', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='control_value', full_name='OtherControl.control_value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=817,
  serialized_end=876,
)

_COMMANDCONTROL.fields_by_name['impedance_command'].message_type = _IMPEDANCECONTROL
_COMMANDCONTROL.fields_by_name['rumble_command'].message_type = _RUMBLECONTROL
_COMMANDCONTROL.fields_by_name['other_messages'].message_type = _OTHERCONTROL
_RUMBLECONTROL.fields_by_name['Thumb'].message_type = _RUMBLECONTROLDATA
_RUMBLECONTROL.fields_by_name['Index'].message_type = _RUMBLECONTROLDATA
_RUMBLECONTROL.fields_by_name['Middle'].message_type = _RUMBLECONTROLDATA
_RUMBLECONTROL.fields_by_name['Ring'].message_type = _RUMBLECONTROLDATA
_RUMBLECONTROL.fields_by_name['Pinky'].message_type = _RUMBLECONTROLDATA
_RUMBLECONTROL.fields_by_name['UtilRumble'].message_type = _RUMBLECONTROLDATA
_IMPEDANCECONTROL.fields_by_name['Thumb'].message_type = _IMPEDANCECONTROLDATA
_IMPEDANCECONTROL.fields_by_name['Index'].message_type = _IMPEDANCECONTROLDATA
_IMPEDANCECONTROL.fields_by_name['Middle'].message_type = _IMPEDANCECONTROLDATA
_IMPEDANCECONTROL.fields_by_name['Ring'].message_type = _IMPEDANCECONTROLDATA
_IMPEDANCECONTROL.fields_by_name['Pinky'].message_type = _IMPEDANCECONTROLDATA
DESCRIPTOR.message_types_by_name['CommandControl'] = _COMMANDCONTROL
DESCRIPTOR.message_types_by_name['RumbleControl'] = _RUMBLECONTROL
DESCRIPTOR.message_types_by_name['RumbleControlData'] = _RUMBLECONTROLDATA
DESCRIPTOR.message_types_by_name['ImpedanceControl'] = _IMPEDANCECONTROL
DESCRIPTOR.message_types_by_name['ImpedanceControlData'] = _IMPEDANCECONTROLDATA
DESCRIPTOR.message_types_by_name['OtherControl'] = _OTHERCONTROL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommandControl = _reflection.GeneratedProtocolMessageType('CommandControl', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDCONTROL,
  '__module__' : 'ctrl_command_pb2'
  # @@protoc_insertion_point(class_scope:CommandControl)
  })
_sym_db.RegisterMessage(CommandControl)

RumbleControl = _reflection.GeneratedProtocolMessageType('RumbleControl', (_message.Message,), {
  'DESCRIPTOR' : _RUMBLECONTROL,
  '__module__' : 'ctrl_command_pb2'
  # @@protoc_insertion_point(class_scope:RumbleControl)
  })
_sym_db.RegisterMessage(RumbleControl)

RumbleControlData = _reflection.GeneratedProtocolMessageType('RumbleControlData', (_message.Message,), {
  'DESCRIPTOR' : _RUMBLECONTROLDATA,
  '__module__' : 'ctrl_command_pb2'
  # @@protoc_insertion_point(class_scope:RumbleControlData)
  })
_sym_db.RegisterMessage(RumbleControlData)

ImpedanceControl = _reflection.GeneratedProtocolMessageType('ImpedanceControl', (_message.Message,), {
  'DESCRIPTOR' : _IMPEDANCECONTROL,
  '__module__' : 'ctrl_command_pb2'
  # @@protoc_insertion_point(class_scope:ImpedanceControl)
  })
_sym_db.RegisterMessage(ImpedanceControl)

ImpedanceControlData = _reflection.GeneratedProtocolMessageType('ImpedanceControlData', (_message.Message,), {
  'DESCRIPTOR' : _IMPEDANCECONTROLDATA,
  '__module__' : 'ctrl_command_pb2'
  # @@protoc_insertion_point(class_scope:ImpedanceControlData)
  })
_sym_db.RegisterMessage(ImpedanceControlData)

OtherControl = _reflection.GeneratedProtocolMessageType('OtherControl', (_message.Message,), {
  'DESCRIPTOR' : _OTHERCONTROL,
  '__module__' : 'ctrl_command_pb2'
  # @@protoc_insertion_point(class_scope:OtherControl)
  })
_sym_db.RegisterMessage(OtherControl)


# @@protoc_insertion_point(module_scope)
